baseURL: "https://www.thedeveco.com"
theme: "up-business-theme"
languageCode: "en-us"

title: "The devEco"

# googleAnalytics: ""

enableEmoji: true

summaryLength: 20

params:
  title: "The Developer Ecosystem"
  description: "A realtime community built by developers for developers. Come join the awesome."
  images: 
    - "images/hero-image.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"


  social:
    linkedin: "#"
    # instagram: "#"
    youtube: "https://youtube.com/@TheDevEco"
    twitter: "https://twitter.com/thedeveco"
    discord: "https://discord.com/channels/620838168794497044/1278241168160718848"

  location:
    - "Everywhere"
    - "No Where"

  contact:
    - "info@thedeveco.com"
    - "192.168.x.x"

  copyright: " All Rights Reserved "

menus:
  main:
    # - name: "Home"
    #   url: "/#hero"
    #   weight: 1

    - name: "Our Mission"
      url: "/about"
      weight: 2

    - name: "The Team"
      url: "/team"
      weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Join Us!"
      url: "/#sign-up"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    # - name: "Home"
    #   url: "/#hero"
    #   weight: 1

    - name: "The Mission"
      url: "/about"
      weight: 2

    - name: "The Team"
      url: "/team"
      weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    - name: "The Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
